Environ. Sci. Technol.: Environmental Science & Technology
Environmental Science and Technology: Environmental Science & Technology
Proc. Natl. Acad. Sci.: Proceedings of the National Academy of Sciences
Proceedings of the National Academy of Sciences of the United States of America: Proceedings of the National Academy of Sciences
Renewable and Sustainable Energy Reviews: Renewable & Sustainable Energy Reviews
Biotechnol. Biofuels Bioprod.: Biotechnology for Biofuels and Bioproducts
J Hazard Mater: Journal of Hazardous Materials
