microalgae: 5
algal-bacterial: 4
wastewater: 4
digestate: 3
piggery: 3
manure: 3
nitrogen removal: 5
ammonia: 3
nitrification: 3
denitrification: 3
TN: 2
nutrient recovery: 3
C/N: 2
low C/N: 3
photobioreactor: 2
co-metabolism: 2
